version: "3.7"
services:
  springproject:
    build:
      context: .
      dockerfile: Dockerfile
    image: breadgood/dockerhub:latest
    ports:
      - 8082:8080
    container_name: springproject_blue
    environment:
      SPRING_DATASOURCE_URL: jdbc:log4jdbc:mysql://mariadb:3306/breadgood?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    networks:
      - database-network

networks:
  database-network:
    external: true
