# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ developer ]

#  pull_request:
#    branches: [ developer ]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    #    needs: [continuous-integration]
    #    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: checkout submodule
        run: |
          git submodule init
          git submodule update

      - name: Grant execute permission for gradlew
        run: chmod +x ./breadgood-server/gradlew

      - name: Build with Gradle
        run: |
          echo $pwd
          ./gradlew clean build -x test
        shell: bash
        working-directory: ./breadgood-server

#      - name: Grant execute permission for scripts
#        run: chmod +x ./scripts

#            - name: Check build file
#              run: sh -c "./scripts/test.sh"

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: breadgood/dockerhub
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: /home/ec2-user/deploy.sh
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          privateKey: ${{ secrets.EC2_PRIVATE_KEY}}
